### ISSUE TITLE
When updating an entity that was not indexed before, it fails

### ISSUE THREAD

**Issue by alexsegura** [acseo/TypesenseBundle#101]
**Describe the bug**

When an entity is updated (triggering the `TypesenseIndexer::postUpdate` method, and subsequently the `TypesenseIndexer::updateDocuments`) BUT, for any reason, the document can't be found in the index, it fails with a `Typesense\Exceptions\ObjectNotFound` when trying to delete the document before trying to reindex it again.  

**To Reproduce**

1. Create a new entity, make sure it is indexed
2. Delete the document manually in Typensense
3. Update the entity

**Expected behavior**

The bundle shouldn't care if the entity isn't indexed yet, it should [upsert](https://typesense.org/docs/0.22.2/api/documents.html#upsert-a-single-document) the entity by default

**Comment by npotier** [comment]
Closing this one as it has been adressed here : https://github.com/acseo/TypesenseBundle/pull/103
