### ISSUE TITLE
"enable_nested_fields" option support

### ISSUE THREAD

**Issue by tbressington** [acseo/TypesenseBundle#112]
**Is your feature request related to a problem? Please describe.**
I am trying to use this package with Symfony 6.4 and PHP 8.2 and I need to enable nested fields so that I can store an array of objects within typesense, however I cannot see any way of setting "enable_nested_fields" to true within the package configuration.

**Describe the solution you'd like**
I would like to be able to enable nested fields by setting "enable_nested_fields: true" for the collection in the acseo_typesense.yaml file.

**Describe alternatives you've considered**
At present the only alternative I have is not to use the package, or spend time trying to add this functionality in myself via a PR.

**Additional context**
N/A

**Comment by tbressington** [comment]
I have raised a PR to add this functionality.

https://github.com/acseo/TypesenseBundle/pull/113

**Comment by npotier** [comment]
Thank you @tbressington, it is now merged and available in tag v0.7.7 of the bundle

**Comment by kabalin** [comment]
@tbressington how this is used in practice? Do you set field type `object[]` and pass object via service converter or there is another way?
(also may be @npotier could answer)
Thanks in advance!
