### ISSUE TITLE
composer require acseo/typesense-bundle Failed on Symfony 7.0.7

### ISSUE THREAD

**Issue by thedok02** [acseo/TypesenseBundle#116]
**Describe the bug**
Install failed on Symfony 7.0.7
**To Reproduce**
1. composer require acseo/typesense-bundle

PS E:\MCMPC\App> composer require acseo/typesense-bundle
./composer.json has been updated
Running composer update acseo/typesense-bundle
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - acseo/typesense-bundle[v0.1, ..., v0.4] require php ^7.1.3 -> your php version (8.2.12) does not satisfy that requirement.
    - acseo/typesense-bundle[v0.5, ..., v0.6] require doctrine/orm ~2.4,>=2.4.5 -> found doctrine/orm[v2.4.5, ..., 2.19.5] but it conflicts with your root composer.json require (^3.1).
    - acseo/typesense-bundle[v0.6.1, ..., v0.7.8] require doctrine/orm ~2.8,>=2.8.0 -> found doctrine/orm[2.8.0, ..., 2.19.5] but it conflicts with your root composer.json require (^3.1).
    - Root composer.json requires acseo/typesense-bundle * -> satisfiable by acseo/typesense-bundle[v0.1, ..., v0.7.8].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require acseo/typesense-bundle:*" to figure out if any version is installable, or "composer require acseo/typesense-bundle:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by npotier** [comment]
Hello, it seems that composer is trying to install an old version of typesensebundle:

` - acseo/typesense-bundle[v0.1, ..., v0.4] require php ^7.1.3 -> your php version (8.2.12) does not satisfy that requirement.` 

Can you try to install the latest version of the bundle : 

`composer require acseo/typesense-bundle:0.7.9`

Hope this helps
