### ISSUE TITLE
"Class %s is not supported" with self reference relationship

### ISSUE THREAD

**Issue by etienneleba** [acseo/TypesenseBundle#17]
I put into my entity a self reference relationship and now I can't populate typepense anymore cause of this exception "Class %s is not supported for Doctrine To Typesense Transformation". Why there is no support when a class has a self reference relationship ?

**Comment by etienneleba** [comment]
Ok it seems that is because doctrine is returning proxy instances instead of real instances, I don't really know why. But a quick fix could be : 
In ACSEO\TypesenseBundle\Transformer\DoctrineToTypesenseTransformer, l35 : $entityClass = str_replace('Proxies\\__CG__\\', '', get_class($entity));

If someone has a clue..

**Comment by npotier** [comment]
Thanks @etienneleba for the feebback.

I guess that you can avoir having Doctrine Proxy object by defining `fetch: EAGER` in your entity, for this relation ?

**Comment by npotier** [comment]
Just in case, if this is still an issue, maybe we could add this in `src/Transformer/DoctrineToTypesenseTransformer.php`,  l34

```php 
use Doctrine\Common\Persistence\Proxy;
        
$entityClass = ($entityClass instanceof Proxy)
            ? get_parent_class($entityClass)
            : get_class($entityClass);
```

**Comment by etienneleba** [comment]
I tested but it created the same thing/bug on another entity. So I didn't want to put "fetch : eager" everywhere

**Comment by etienneleba** [comment]
Ok I will try that and I will create a pull request if it works

**Comment by npotier** [comment]
Hello @etienneleba dit it works ? Thank you for your feedback
