### ISSUE TITLE
Couldn't connect to server for "http://localhost:8108/collections/articles

### ISSUE THREAD

**Issue by thornade05** [acseo/TypesenseBundle#20]
Hello,
I try your bundle but after install it, i launch typesense:create.

commande return : Couldn't connect to server for "http://localhost:8108/collections/articles.

I use symfony 5.1 (skeleton) / php7.3.
Thk for your help.

**Comment by npotier** [comment]
Hi @thornade05 are you sure that your typesense instance is up and running ?

Can you try this command (please change the `<API_KEY>`)  and tell  me what is the output :

```bash
curl -H "X-TYPESENSE-API-KEY: <API_KEY>" "http://localhost:8108/collections"
```

**Comment by thornade05** [comment]
Hi,

The command return:
Curl: (7)  Failed to connect to localhost port 8108: Connections refused.




Le lun. 7 déc. 2020 à 15:07, Nicolas Potier <notifications@github.com> a
écrit :

**Comment by npotier** [comment]
Yes, so **Typesense is not running or may not be running on port 8108**. Did you install it ? Are you sure it is running ? 

You should check the Typesense documentation :  https://typesense.org/docs/0.17.0/guide/

if you launched Typesense with Docker you should check on wich port typesense is running (with `docker ps` for example).

**Comment by thornade05** [comment]
Ok, thk for tour help. I install curl certificat ans open port 8108.
I have install the server , sorry i thought i have installed.
It  resolved , thk.

Le lun. 7 déc. 2020 à 16:54, Nicolas Potier <notifications@github.com> a
écrit :

**Comment by npotier** [comment]
You are welcome.

**Comment by marcus7777** [comment]
Hi friends,
I'm got the some error:

```
➜  ~ sudo systemctl status typesense-server.service

● typesense-server.service - Typesense Server
     Loaded: loaded (/etc/systemd/system/typesense-server.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2022-05-09 12:29:24 BST; 1 day 22h ago
       Docs: https://typesense.org
   Main PID: 58951 (typesense-serve)
      Tasks: 1 (limit: 17852)
     Memory: 360.0K
        CPU: 4ms
     CGroup: /system.slice/typesense-server.service
             └─58951 /usr/bin/typesense-server --config=/etc/typesense/typesense-server.ini

May 09 12:29:24 marcus-HP-EliteBook-735-G5 systemd[1]: Started Typesense Server.
➜  ~ curl -H "X-TYPESENSE-API-KEY: IJTu..." "http://localhost:8108/health"     
curl: (7) Failed to connect to localhost port 8108: Connection refused
➜  ~ 
```
