### ISSUE TITLE
There are no commands defined in the "typesense" namespace

### ISSUE THREAD

**Issue by thornade05** [acseo/TypesenseBundle#21]
Hello,
I install typesense server: ok
install acseo/TypesenseBundle:ok
setup in .env and package : ok

But i have an error when i launch command :  php bin/console typesense:create, return commande:
There are no commands defined in the "typesense" namespace.
User Deprecated: Not passing a connection provider as the first constructor argument is deprecated

I use SF 5.1

So, i try php bin/console typesense =>  Command "typesense" is not defined.

When i launch php bin/console => i not see typense command

I launch: composer dump-autoload

Resolved
Thk

**Comment by eldinomick** [comment]
on symfony 5.2 and 5.3, composer dump-autoload not repair this problem.

**Comment by villarwt** [comment]
Is this ever going to get fixed?

**Comment by villarwt** [comment]
Could have something to do with composer and the shift between versions. Either way, it can be solved by doing what is suggsted in the following resolved issue: https://github.com/acseo/TypesenseBundle/issues/49#
