### ISSUE TITLE
PHP8 compatibility

### ISSUE THREAD

**Issue by ColonelMoutarde** [acseo/TypesenseBundle#27]
Hello, can you add php8 compatibility for this great bundle ?

**Comment by pierre-H** [comment]
Hello,

It would be also great to have the possibility to declare the mapping with PHP 8 attributes.

**Comment by npotier** [comment]
Hello @ColonelMoutarde PHP8 is available since the version 0.5 of the Bundle.

@pierre-H it's a nice idea indeed 👍

**Comment by ColonelMoutarde** [comment]
Please @pierre-H create an another issue :)
