### ISSUE TITLE
Proxy classes not working

### ISSUE THREAD

**Issue by tsdevelopment** [acseo/TypesenseBundle#33]
Whenever Doctrine returns a ProxClass (for example "Proxies\__CG__\App\Entity\MyClass" the `postUpdate` method will not work. Please use the following code to get the "real" class name:

```php
# vendor/acseo/typesense-bundle/src/EventListener/TypesenseIndexer.php

<?php

namespace ACSEO\TypesenseBundle\EventListener;

[...]
use Doctrine\Common\Util\ClassUtils;

class TypesenseIndexer
{

    public function postUpdate(LifecycleEventArgs $args)
        {
            $entity = $args->getObject();
            $entityClassname = ClassUtils::getClass($entity);

            [...]
        }
}
```

This should also used in the other methods where you use `get_class` to retrieve the class name.

**Comment by npotier** [comment]
Hello @tsdevelopment thank you for reporting this issue. 

it has been solved with the PR : https://github.com/acseo/TypesenseBundle/pull/34

**Comment by npotier** [comment]
I'm closing the issue now, feel free to reopen it if anything goes wrong.
