### ISSUE TITLE
There are no commands defined in the "typesense" namespace.  

### ISSUE THREAD

**Issue by villarwt** [acseo/TypesenseBundle#49]
**Describe the bug**
The typsense command is not detected in SF version 5.3+

**To Reproduce**
Follow **installation** and **configuration** instructions as per the readme file located at:  https://github.com/acseo/TypesenseBundle#readme

Run the typesense:create command.
`$ php bin/console typesense:create`

**Expected behavior**
It works.

**Screenshots**

![image](https://user-images.githubusercontent.com/67297826/151498254-c38a33db-9844-43de-a43a-8772224779e4.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - PHP 7.4

**Additional context**
`composer dump-autoload `
as mentioned in another report doesn't fix it.

**Comment by npotier** [comment]
Hello @villarwt thank you for your message.

I've tried to reproduce your error.

Can you please tell me if your configuration file is `config/packages/acseo_typesense.yml` or `config/packages/acseo_typesense.yaml` (notice the difference in the filename extension)

I've noticed that `.yaml` extension is mandatory :

```bash

### OK ###
➜  test-typesense git:(main) ✗ ls -al config/packages/acseo_typesense.yaml 
-rw-r--r--  1 nicolaspotier  staff  2041 31 jan 12:27 config/packages/acseo_typesense.yaml
➜  test-typesense git:(main) ✗ symfony console typesense                  
[critical] Error thrown while running command "typesense". Message: "Command "typesense" is not defined.

Did you mean one of these?
    typesense:create
    typesense:populate"
         
### NOT OK ###

➜  test-typesense git:(main) ✗ mv config/packages/acseo_typesense.yaml config/packages/acseo_typesense.yml  
➜  test-typesense git:(main) ✗ symfony console typesense                                                  
[critical] Error thrown while running command "typesense". Message: "Command "typesense" is not defined."

  Command "typesense" is not defined.  
                                       
➜  test-typesense git:(main) ✗ 
```

**Comment by villarwt** [comment]
Hi @npotier 

Good to meet you and thank you for getting back to me.

There seems to be an issue with 0.6.6
I've tried with yaml and yml extensions.

```
villar@843285d099c7:/usr/src/app$ ls -lah config/packages/acseo_typesense.yaml 
-rw-rw-r-- 1 villar villar 2.0K Jan 31 15:43 config/packages/acseo_typesense.yaml
villar@843285d099c7:/usr/src/app$ ls -la config/packages/acseo_typesense.yaml 
-rw-rw-r-- 1 villar villar 2041 Jan 31 15:43 config/packages/acseo_typesense.yaml
villar@843285d099c7:/usr/src/app$ symfony console typesense
                                       
  Command "typesense" is not defined.  
                                       
villar@843285d099c7:/usr/src/app$ 

```

Here's what I'm working with:
```
villar@843285d099c7:/usr/src/app$ symfony composer show | grep -E 'symfony/framework|typesense'
acseo/typesense-bundle              v0.6.6  This bundle provides integration with Typesense in Symfony
symfony/framework-bundle            v5.4.4  Provides a tight integration between Symfony components and the Symfony full-stack framework
typesense/typesense-php             v4.7.0  PHP client for Typesense Search Server: https://github.com/typesense/typesense

```

**Comment by npotier** [comment]
Nice to meet you too.

I've tried to reproduce the error with the same version of TypesenseBundle, but it works for me.

Just to be sure, can you try to clear your cache after you renamed the file extension ?

Here is what I have:

```bash
➜  test-typesense git:(main) ✗ symfony php -v                                               
PHP 8.1.2 (cli) (built: Jan 19 2022 02:23:16) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2, Copyright (c), by Zend Technologies

➜  test-typesense git:(main) ✗ symfony composer show | grep -E 'symfony/framework|typesense'
acseo/typesense-bundle              v0.6.6  This bundle provides integration with Typesense in Symfony
symfony/framework-bundle            v5.4.4  Provides a tight integration between Symfony components and the Symfony full-stack framework
typesense/typesense-php             v4.7.0  PHP client for Typesense Search Server: https://github.com/typesense/typesense

➜  test-typesense git:(main) ✗ symfony console cache:clear

 // Clearing the cache for the dev environment with debug true                                                          
                                                                                                                        
 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.  
                                         
➜  test-typesense git:(main) ✗ ls -al config/packages/acseo_typesense.yaml 
-rw-r--r--  1 nicolaspotier  staff  2040 31 jan 17:29 config/packages/acseo_typesense.yaml
                                                                                                                        
➜  test-typesense git:(main) ✗ symfony console typesense                                    
                                       
  Command "typesense" is not defined.  
                                       
  Did you mean one of these?           
      typesense:create                 
      typesense:import

**Comment by villarwt** [comment]
Hi again @npotier 

Thank you for giving this some attention. Issue resolved.

Some quick instructions which fixed the ambiguous issue for me:

1. Updating the filename to from acseo_typesesense.yml to acseo_typesesense.yaml (this alone was not enough)
2. Clear the cache via bin/console cache:clear --env=prod && bin/console cache:clear --env=dev
3. If this does not work, then try to remove and reinstall the bundle in composer - this could have inadvertently cleared the cache as suggested by @npotier which led me to believe that there was an issue with 0.6.6

**Comment by DavidMasseDev** [comment]
> Hi again @npotier
> 
> Thank you for giving this some attention. Issue resolved.
> 
> Some quick instructions which fixed the ambiguous issue for me:
> 
>     1. Updating the filename to from acseo_typesesense.yml to acseo_typesesense.yaml (this alone was not enough)
> 
>     2. Clear the cache via bin/console cache:clear --env=prod && bin/console cache:clear --env=dev
> 
>     3. If this does not work, then try to remove and reinstall the bundle in composer - this could have inadvertently cleared the cache as suggested by @npotier which led me to believe that there was an issue with 0.6.6

Works for me too. Thank you !
