### ISSUE TITLE
TypesenseBundle v0.6 is not compatible with doctrine orm 2.4.5 to 2.7.5

### ISSUE THREAD

**Issue by Nape** [acseo/TypesenseBundle#57]
**Describe the bug**

In the ImportCommande.php on line 76 : 
$entities = $q->toIterable(); cause problem because it only appear in doctrine ^2.8 and up.
I think It should be : 
$q->iterate(); on line 76 
and 
$data = $this->transformer->convert($entity[0]); on line 83

"require": {
        "php": "^7.4||^8.0",
      **"doctrine/orm": "~2.4,>=2.4.5",**
        "symfony/framework-bundle": "^3.4|^4.3|^5",
        ...
    },

**To Reproduce**
Run the import command with doctrine/orm 2.4.5

**Comment by npotier** [comment]
Hello @Nape indeed TypesenseBundle requires `doctrine/orm ^2.8` minimum in horder to have the `toIterable()` method. 

The `iterate()` method is deprecated (https://github.com/doctrine/orm/issues/8463), and `doctrine/orm 2.8` was released in 2020, so I don't feel like handling this case.

I suggest you to upgrade `doctrine/orm` in your project if you can.

**Comment by Nape** [comment]
Merci pour le suivi !
