### ISSUE TITLE
update the bundle to add the missing configuration options

### ISSUE THREAD

**Issue by tamsirgueye** [acseo/TypesenseBundle#59]
**I wanted to use the `token_separators` option. Unfortunately it is not yet available in the bundle. And I think this option is indispensable for Typesense.**

**Comment by tamsirgueye** [comment]
I have added these two options in my fork.
- `token_separators`
> Customizable word separators: define a list of special characters via the `token_separators` configuration during schema creation. These characters are then used as word separators, in addition to space and new-line characters.
>
- `symbols_to_index`
>Index and search special characters: define a list of special characters that will be indexed as text via the `symbols_to_index` configuration during schema creation.
>
>
See
- [https://github.com/acseo/TypesenseBundle/pull/60](My pull request)
- [https://typesense.org/docs/0.22.0/api/#what-s-new](Official doc)

**Comment by npotier** [comment]
Thank you. I’m closing this issue thanks to your PR
