### ISSUE TITLE
Installation failed on Symfony 5.4

### ISSUE THREAD

**Issue by developerEinpix** [acseo/TypesenseBundle#64]
When I try to install the bundle using `composer require acseo/typesense-bundle` it is displaying the error as below.

`PHP Version` 8.0
`http-client` ^6.0 (It requires `symfony/http-client-contracts: ^3.0`)

```
Root composer.json requires acseo/typesense-bundle ^0.6.7 -> satisfiable by acseo/typesense-bundle[v0.6.7].
    - acseo/typesense-bundle v0.6.7 requires symfony/http-client-contracts ^1.0|^2.0 -> found symfony/http-client-contracts[v1.1.1, ..., v1.1.13, v2.0.0, ..., v2.5.2] but the package is fixed to v3.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
```

**Comment by npotier** [comment]
Hello, 

Thank you for your message. You can try version `>= 0.7` of the bundle, it should be good

As you can see here https://github.com/acseo/TypesenseBundle/blob/v0.7.0/composer.json the dependecy has been updated with `"symfony/http-client-contracts": "^1.0|^2.0|^3.0",`
