### ISSUE TITLE
There are no commands defined in the "typesense" namespace. 

### ISSUE THREAD

**Issue by guillaume-a** [acseo/TypesenseBundle#67]
**Describe the bug**
There are no commands defined in the "typesense" namespace. 

**To Reproduce**
1. Init a new symfony project ` symfony new --dir=typesense --webapp --version=6.0`
2. Require this bundle `symfony composer require acseo/typesense-bundle`
3. Define a default config with a simple entity
4. Try to launch command `symfony console typesense:create`

I tried to set this on symfony 6.2, 6.1 and 6.0.
Same result each time.

**Comment by guillaume-a** [comment]
Edit : Seems to work if I rename the config file `acseo_typesense.yaml` instead of `acseo_typesense.yml`

**Comment by kl3sk** [comment]
Confirmed on my side. Thanks @guillaume-a
