### ISSUE TITLE
Compatibility with Doctrine 2.x.x is broken

### ISSUE THREAD

**Issue by lucasferraro** [acseo/TypesenseBundle#77]
**Describe the bug**
After [this commit](https://github.com/acseo/TypesenseBundle/commit/00a67b2c6b0a929ef24302e60c5ab5bcb0edcf87) compatibility with versions of Doctrine <3.x.x was lost. 

**To Reproduce**
When an import is requested using Doctrine 2.x.x the following error is thrown:
```
18:40:24 CRITICAL  [console] Error thrown while running command "typesense:import". Message: "Call to undefined method Doctrine\DBAL\Configuration::setMiddlewares()" ["exception" => Error { …},"command" => "typesense:import","message" => "Call to undefined method Doctrine\DBAL\Configuration::setMiddlewares()"] ["token" => null]

In ImportCommand.php line 70:
                                                                               
  Attempted to call an undefined method named "setMiddlewares" of class "Doct  
  rine\DBAL\Configuration".
```

**Expected behavior**
Import command should work as expected with versions of Doctrine <3.0.0 (or at least with the [minimum Doctrine version supported](https://github.com/acseo/TypesenseBundle/blob/9cc51e6274f60237a40e28c0df7d56d4aa8dbe87/composer.json#L14))

A fix for this is already pushed and waiting for a review [here](https://github.com/acseo/TypesenseBundle/pull/78).

**Comment by npotier** [comment]
Hello @lucasferraro thank you for reporting this issue and proposing a PR.

it has been merged.

**Comment by lucasferraro** [comment]
> Hello @lucasferraro thank you for reporting this issue and proposing a PR.
> 
> it has been merged.

:) I'm happy to contribute
