### ISSUE TITLE
Not index during test

### ISSUE THREAD

**Issue by etienneleba** [acseo/TypesenseBundle#8]
We should create an option to put typesense off during test. Cause it's not possible to run test with typesense.

**Comment by etienneleba** [comment]
I was thinking to do like the mailer bundle. Put the url environment variable of typesense to null in the .env.test, and check in the code if it's null or no, what do you do think ? 
And I was wondering where to put the check of the value ? I was thinking in the TypesenseClient

**Comment by npotier** [comment]
Fixed
